export let options = [
    { value: "AH", label: "Albert Hall" },
    { value: "All UP Workers Union", label: "All UP Workers Union" },
    { value: "AECH", label: "Alumni Engineers Centennial Hall" },
    { value: "Carillon Tower and Plaza", label: "Andres Bonifacio Centennial Carillon Tower and Plaza" },
    { value: "Ang Bahay ng Alumni", label: "Ang Bahay ng Alumni" },
    { value: "A2", label: "Area 2 Residential Community" },
    { value: "Asian Center", label: "Asian Center" },
    { value: "AIT", label: "Asian Institute of Tourism" },
    { value: "Balay Kalinaw", label: "Balay Kalinaw" },
    { value: "Balay Tsanseslor", label: "Balay Tsanseslor" },
    { value: "FC", label: "Bulwagang Rizal" },
    { value: "UPCIS", label: "Center for International Studies" },
    { value: "CDC", label: "Child Development Center" },
    { value: "Church of the Risen Lord", label: "Church of the Risen Lord" },
    { value: "CA", label: "College of Architecture" },
    { value: "CA1", label: "College of Architecture Bldg. 1" },
    { value: "CAL", label: "College of Arts and Letters" },
    { value: "Eduk", label: "College of Education" },
    { value: "CFA", label: "College of Fine Arts" }, 
    { value: "CHE", label: "College of Home Economics" },
    { value: "CHK", label: "College of Human Kinetics" },
    { value: "Plaridel Hall", label: "College of Mass Communication" },
    { value: "CMu", label: "College of Music" },
    { value: "CS Admin", label: "College of Science Administration Building" },
    { value: "CSLib", label: "College of Science Library" },
    { value: "CHED", label: "Commission on Higher Education" },
    { value: "CHR", label: "Commission on Human Rights" },
    { value: "CDL", label: "Crafts and Design Laboratory" },
    { value: "EEEI", label: "Electrical and Electronics Engineering Institute" },
    { value: "EH", label: "Enriquez Hall" },
    { value: "Executive House", label: "Executive House" },
    { value: "FI", label: "Film Institute" },
    { value: "Gus2", label: "Gusali 2" },
    { value: "Hardin ng Doña Aurora Housing", label: "Hardin ng Doña Aurora Housing" },
    { value: "IMath", label: "Institute of Mathematics" },
    { value: "IESM", label: "Institute of Environmental Science and Meterology" },
    { value: "Kalinga Day Care Center", label: "Kalinga Day Care Center" },
    { value: "MC", label: "Media Center and DZUP Station" },
    { value: "NIGS", label: "National Institute of Geological Sciences" },
    { value: "National Science Complex Amphitheater", label: "National Science Complex Amphitheater" },
    { value: "Oblation", label: "Oblation Plaza" },
    { value: "AS", label: "Palma Hall" },
    { value: "TH", label: "Tolentino Hall" },
    { value: "VH", label: "Villadolid Hall" },
];